// (NOTE: autogenerated file; do not modify)
import { connectWidget } from 'apptile-core';
import { ReactComponent, WidgetConfig, WidgetEditors, PropertySettings } from './components/component';

const pluginListing = {
  labelPrefix: 'plantdashboard',
  type: 'widget',
  name: 'plantdashboard',
  description: 'Basic plugin created from template',
  layout: {
    width: 50,
    height: 30,
  },
  section: 'SDK',
  icon: 'badge',
  manifest: {
    directoryName: 'plantdashboard',
  }
};

export default connectWidget(
  'plantdashboard',
  ReactComponent,
  WidgetConfig,
  null,
  WidgetEditors,
  {
    propertySettings: PropertySettings,
    widgetStyleConfig: [],
    pluginListing,
    docs: {},
  }
);
